export const SET_FILMS_LIST = 'SET_FILMS_LIST';
export const SET_MATCHED_FILMS = 'SET_MATCHED_FILMS';
export const IS_LOADING = 'IS_LOADING';
export const LOADING_COVER_IMAGES = 'LOADING_COVER_IMAGES';
